spring:
  application:
    name: zen-iot
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_zen_iot
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
