spring:
  application:
    name: zen-iot
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_zen_iot
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8088
secret:
  key: "UiTXuwC4pHqsLoHGimE1aZ686FAdKDz1BPVL2JMzTsYv8Y6YJHpJnKrjtK23XqMS"
  expiration: 2592000 # 30 * 24 * 60 * 60 s  -- 30天

transport:
  mqtt:
    ssl:
      enabled: ${MQTT_SSL_ENABLE:true}
      credentials:
        type: PEM
        pem:
          cert-file: classpath:${MQTT_SSL_CERT_PEM:server_cert.pem}
          key-file: classpath:${MQTT_SSL_KEY_PEM:server_key.pem}
          key-password: ${MQTT_SSL_PWD:mqtt}
