spring:
  application:
    name: zen-iot
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_zen_iot
    username: postgres
    password: postgres
  flyway:
    enabled: false
  security:
    user:
      name: admin
      password: 123